language: python
python: 2.7
services:
  - redis-server
addons:
  postgresql: "9.3"
env:
  - TOXENV=py26-dj13
  - TOXENV=py26-dj14
  - TOXENV=py26-dj15
  - TOXENV=py26-dj16
  - TOXENV=py27-dj13
  - TOXENV=py27-dj14
  - TOXENV=py27-dj15
  - TOXENV=py27-dj16
  - TOXENV=py27-dj17
  - TOXENV=py27-djmaster
  - TOXENV=py33-dj15
  - TOXENV=py33-dj16
  - TOXENV=py33-dj17
  - TOXENV=py33-djmaster
  - TOXENV=py34-dj15
  - TOXENV=py34-dj16
  - TOXENV=py34-dj17
  - TOXENV=py34-djmaster
  - TOXENV=flakes
matrix:
  allow_failures:
    - env: "TOXENV=py27-djmaster"
    - env: "TOXENV=py33-djmaster"
    - env: "TOXENV=py34-djmaster"
install:
  - pip install tox
before_script:
  - psql -U postgres -c "create extension postgis"
script:
  - tox
